server:
  port: 8080

spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:h2:file:./data/gateway-service;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

gem:
  security:
    jwt-secret: "change-me-super-secret-key-please-32bytes-min"
    jwt-ttl-seconds: 3600
  rabbitmq:
    exchange: domain.events
    inventory-queue: inventory.q
    notification-queue: notification.q
